apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: infratrack-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infratrack-frontend
  template:
    metadata:
      labels:
        app: infratrack-frontend
    spec:
      containers:
      - name: infratrack-frontend
        image: kubeumar/infratrack-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
